


export const productList = [
      {
            id: 1,
            product_name: "Soft & Comfortable Cotton Half Sleeve",
            img: ["/assets/images/products/01.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "soft-comfortable-cotton-half-sleeve",
            price: 289,
            discount_price: 270,
            discount: 2,
            free_delivery: 1,
            total_review: 37,
            avg_review: 3,
            total_sell: 150,
            brand_id: 101,
            category_id: 1,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 501,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 2,
            product_name: "Custom Logo Design Polyester Spandex Workout",
            img: ["/assets/images/products/02.png", "/assets/images/products/08.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "custom-logo-design-polyester-spandex",
            price: 389,
            discount_price: 370,
            discount: 0,
            free_delivery: 1,
            total_review: 52,
            avg_review: 4,
            total_sell: 230,
            brand_id: 102,
            category_id: 2,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 502,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 3,
            product_name: "Charger Protector Case for iPhone 15 Pro",
            img: ["/assets/images/products/03.png", "/assets/images/products/02.png", "/assets/images/products/08.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "charger-protector-case-iphone-15-pro",
            price: 99,
            discount_price: 90,
            discount: 9,
            free_delivery: 0,
            total_review: 47,
            avg_review: 3,
            total_sell: 300,
            brand_id: 103,
            category_id: 3,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 503,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 4,
            product_name: "Wireless Bluetooth Earbuds with Noise Cancellation",
            img: ["/assets/images/products/04.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/08.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "wireless-bluetooth-earbuds-noise-cancellation",
            price: 199,
            discount_price: 180,
            discount: 0,
            free_delivery: 0,
            total_review: 110,
            avg_review: 4,
            total_sell: 400,
            brand_id: 104,
            category_id: 4,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 504,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 5,
            product_name: "4K Ultra HD",
            img: ["/assets/images/products/05.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/08.png", "/assets/images/products/06.png"],
            slug: "4k-ultra-hd-smart-led-tv-55-inch",
            price: 499,
            discount_price: 450,
            discount: 12,
            free_delivery: 1,
            total_review: 73,
            avg_review: 4,
            total_sell: 90,
            brand_id: 105,
            category_id: 5,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 505,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 6,
            product_name: "Ergonomic Office Chair with Lumbar Support",
            img: ["/assets/images/products/06.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/08.png"],
            slug: "ergonomic-office-chair-lumbar-support",
            price: 159,
            discount_price: 140,
            discount: 12,
            free_delivery: 1,
            total_review: 35,
            avg_review: 5,
            total_sell: 200,
            brand_id: 106,
            category_id: 6,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 506,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 7,
            product_name: "Smart Watch with Heart Rate Monitor",
            img: ["/assets/images/products/07.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "smart-watch-heart-rate-monitor",
            price: 79,
            discount_price: 70,
            discount: 8,
            free_delivery: 0,
            total_review: 95,
            avg_review: 4,
            total_sell: 280,
            brand_id: 107,
            category_id: 7,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 507,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 8,
            product_name: "Gaming Mouse with RGB Lights",
            img: ["/assets/images/products/08.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "gaming-mouse-rgb-lights",
            price: 49,
            discount_price: 45,
            discount: 4,
            free_delivery: 1,
            total_review: 62,
            avg_review: 5,
            total_sell: 320,
            brand_id: 108,
            category_id: 8,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 508,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 9,
            product_name: "Waterproof Fitness Tracker for Swimming",
            img: ["/assets/images/products/09.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "waterproof-fitness-tracker-swimming",
            price: 99,
            discount_price: 85,
            discount: 14,
            free_delivery: 1,
            total_review: 85,
            avg_review: 4,
            total_sell: 150,
            brand_id: 109,
            category_id: 7,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 509,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 10,
            product_name: "Portable Power Bank 20000mAh",
            img: ["/assets/images/products/10.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "portable-power-bank-20000mah",
            price: 89,
            discount_price: 79,
            discount: 11,
            free_delivery: 1,
            total_review: 140,
            avg_review: 5,
            total_sell: 350,
            brand_id: 110,
            category_id: 9,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 510,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 11,
            product_name: "Portable Power Bank 20000mAh",
            img: ["/assets/images/products/11.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "portable-power-bank-20000mah",
            price: 89,
            discount_price: 79,
            discount: 11,
            free_delivery: 1,
            total_review: 140,
            avg_review: 5,
            total_sell: 350,
            brand_id: 110,
            category_id: 9,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 510,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 12,
            product_name: "Portable Power Bank 20000mAh",
            img: ["/assets/images/products/12.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "portable-power-bank-20000mah",
            price: 89,
            discount_price: 79,
            discount: 11,
            free_delivery: 1,
            total_review: 140,
            avg_review: 5,
            total_sell: 350,
            brand_id: 110,
            category_id: 9,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 510,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 13,
            product_name: "Portable Power Bank 20000mAh",
            img: ["/assets/images/products/03.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "portable-power-bank-20000mah",
            price: 89,
            discount_price: 79,
            discount: 11,
            free_delivery: 1,
            total_review: 140,
            avg_review: 5,
            total_sell: 350,
            brand_id: 110,
            category_id: 9,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 510,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 14,
            product_name: "Portable Power Bank 20000mAh",
            img: ["/assets/images/products/01.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "portable-power-bank-20000mah",
            price: 89,
            discount_price: 79,
            discount: 11,
            free_delivery: 1,
            total_review: 140,
            avg_review: 5,
            total_sell: 350,
            brand_id: 110,
            category_id: 9,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 510,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      },
      {
            id: 15,
            product_name: "Portable Power Bank 20000mAh",
            img: ["/assets/images/products/07.png", "/assets/images/products/02.png", "/assets/images/products/03.png", "/assets/images/products/04.png", "/assets/images/products/05.png", "/assets/images/products/06.png"],
            slug: "portable-power-bank-20000mah",
            price: 89,
            discount_price: 79,
            discount: 11,
            free_delivery: 1,
            total_review: 140,
            avg_review: 5,
            total_sell: 350,
            brand_id: 110,
            category_id: 9,
            size_chart: ["s", "m", "l", "xl", "xxl"],
            marcent_id: 510,
            color: ["161616", "FD651C", "0085FF", "FF0000", "FFB800", "C03BFF", "465569", "FFFFFF"]
      }
];
